# Generated by Django 5.2 on 2025-04-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Settings', max_length=100)),
                ('n', models.FloatField(default=0.013)),
                ('b', models.FloatField(default=1.0)),
                ('alpha', models.FloatField(default=45.0)),
                ('S', models.FloatField(default=0.001)),
                ('rho', models.FloatField(default=1000.0)),
                ('g', models.FloatField(default=9.81)),
                ('Pd', models.FloatField(default=9810.0)),
            ],
        ),
        migrations.CreateModel(
            name='FlowCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.FloatField(help_text='Water height in meters')),
                ('A', models.FloatField(blank=True, null=True)),
                ('P', models.FloatField(blank=True, null=True)),
                ('R', models.FloatField(blank=True, null=True)),
                ('V', models.FloatField(blank=True, null=True)),
                ('Q', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.channelsettings')),
            ],
        ),
        migrations.DeleteModel(
            name='WaterData',
        ),
    ]
