# Generated by Django 5.2 on 2025-04-06 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_channelsettings_flowcalculation_delete_waterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsettings',
            name='Pd',
            field=models.FloatField(default=9810.0, verbose_name='Bosim Pd (Pa)'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='S',
            field=models.FloatField(default=0.001, verbose_name='Gidravlik qiyalik S'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='alpha',
            field=models.FloatField(default=45.0, verbose_name='Yon devor burchagi α (gradus)'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='b',
            field=models.FloatField(default=1.0, verbose_name='Kanal eni b (m)'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='g',
            field=models.FloatField(default=9.81, verbose_name='Gravitatsiya g (m/s²)'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='n',
            field=models.FloatField(default=0.013, verbose_name='Qo‘polilik koeffitsienti n'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='name',
            field=models.CharField(default='Default Settings', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='rho',
            field=models.FloatField(default=1000.0, verbose_name='Zichlik ρ (kg/m³)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='A',
            field=models.FloatField(blank=True, null=True, verbose_name='Yuza A (m²)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='P',
            field=models.FloatField(blank=True, null=True, verbose_name='Perimetr P (m)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='Q',
            field=models.FloatField(blank=True, null=True, verbose_name='Suv sarfi Q (m³/s)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='R',
            field=models.FloatField(blank=True, null=True, verbose_name='Gidravlik radius R (m)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='V',
            field=models.FloatField(blank=True, null=True, verbose_name='Oqim tezligi V (m/s)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='h',
            field=models.FloatField(help_text='Suv sathi metrda', verbose_name='Suv balandligi h (m)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.channelsettings', verbose_name='Kanal sozlamalari'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='O‘lchov vaqti'),
        ),
    ]
