# Generated by Django 5.2 on 2025-04-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_channelsettings_pd_alter_channelsettings_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyFlowSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Soat bo‘yicha vaqt')),
                ('h', models.FloatField(blank=True, null=True, verbose_name='O‘rtacha h (m)')),
                ('A', models.FloatField(blank=True, null=True, verbose_name='A (m²)')),
                ('P', models.FloatField(blank=True, null=True, verbose_name='P (m)')),
                ('R', models.FloatField(blank=True, null=True, verbose_name='R (m)')),
                ('V', models.FloatField(blank=True, null=True, verbose_name='V (m/s)')),
                ('Q', models.FloatField(blank=True, null=True, verbose_name='Q (m³/s)')),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.channelsettings', verbose_name='Kanal sozlamalari')),
            ],
            options={
                'verbose_name': 'Soatlik oqim',
                'verbose_name_plural': 'Soatlik oqimlar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
