# Generated by Django 5.2 on 2025-04-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_hourlyflowsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowcalculation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Real vaqtdagi oqim', 'verbose_name_plural': 'Real vaqtdagi oqimlar'},
        ),
        migrations.CreateModel(
            name='MonthlyFlowSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Oylik vaqt (boshi)')),
                ('h', models.FloatField(blank=True, null=True, verbose_name='O‘rtacha h (m)')),
                ('A', models.FloatField(blank=True, null=True, verbose_name='A (m²)')),
                ('P', models.FloatField(blank=True, null=True, verbose_name='P (m)')),
                ('R', models.FloatField(blank=True, null=True, verbose_name='R (m)')),
                ('V', models.FloatField(blank=True, null=True, verbose_name='V (m/s)')),
                ('Q', models.FloatField(blank=True, null=True, verbose_name='Q (m³/s)')),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.channelsettings', verbose_name='Kanal sozlamalari')),
            ],
            options={
                'verbose_name': 'Oylik oqim',
                'verbose_name_plural': 'Oylik oqimlar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyFlowSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Haftalik vaqt (boshi)')),
                ('h', models.FloatField(blank=True, null=True, verbose_name='O‘rtacha h (m)')),
                ('A', models.FloatField(blank=True, null=True, verbose_name='A (m²)')),
                ('P', models.FloatField(blank=True, null=True, verbose_name='P (m)')),
                ('R', models.FloatField(blank=True, null=True, verbose_name='R (m)')),
                ('V', models.FloatField(blank=True, null=True, verbose_name='V (m/s)')),
                ('Q', models.FloatField(blank=True, null=True, verbose_name='Q (m³/s)')),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.channelsettings', verbose_name='Kanal sozlamalari')),
            ],
            options={
                'verbose_name': 'Haftalik oqim',
                'verbose_name_plural': 'Haftalik oqimlar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
