# Generated by Django 5.2 on 2025-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_flowcalculation_options_monthlyflowsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsettings',
            name='max_height',
            field=models.FloatField(default=1.2, verbose_name='Maksimal suv balandligi (h)'),
        ),
        migrations.AddField(
            model_name='channelsettings',
            name='min_height',
            field=models.FloatField(default=0.3, verbose_name='Minimal suv balandligi (h)'),
        ),
    ]
