# Generated by Django 5.2 on 2025-04-09 20:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_channelsettings_max_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsettings',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif (HTML)'),
        ),
        migrations.AddField(
            model_name='channelsettings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='channel_images/', verbose_name='Kanal rasmi'),
        ),
    ]
