# Generated by Django 5.2 on 2025-04-12 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_channelsettings_description_channelsettings_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsettings',
            name='Pd',
        ),
        migrations.AddField(
            model_name='flowcalculation',
            name='Pd',
            field=models.FloatField(default=1, help_text='Sensor orqali o‘lchanadi', verbose_name='Gidrostatik bosim Pd (Pa)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlyflowsummary',
            name='Pd',
            field=models.FloatField(blank=True, null=True, verbose_name='Gidrostatik bosim Pd (Pa)'),
        ),
        migrations.AddField(
            model_name='monthlyflowsummary',
            name='Pd',
            field=models.FloatField(blank=True, null=True, verbose_name='Gidrostatik bosim Pd (Pa)'),
        ),
        migrations.AddField(
            model_name='weeklyflowsummary',
            name='Pd',
            field=models.FloatField(blank=True, null=True, verbose_name='Gidrostatik bosim Pd (Pa)'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='g',
            field=models.FloatField(default=9.81, verbose_name='Erkin tushushi tezlanishi g (m/s²)'),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='n',
            field=models.FloatField(default=0.013, verbose_name="G'adir budurlik koyfitsienti n"),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='Hisoblangan suv balandligi h (m)'),
        ),
        migrations.AlterField(
            model_name='flowcalculation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='O‘lchov vaqti'),
        ),
        migrations.AlterField(
            model_name='hourlyflowsummary',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='Hisoblangan h (m)'),
        ),
        migrations.AlterField(
            model_name='hourlyflowsummary',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monthlyflowsummary',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='Hisoblangan h (m)'),
        ),
        migrations.AlterField(
            model_name='monthlyflowsummary',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weeklyflowsummary',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='Hisoblangan h (m)'),
        ),
        migrations.AlterField(
            model_name='weeklyflowsummary',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
